### PR TITLE
Enable NUMA-aware GPU worker binding, config updates after fixes 

### LINKED ISSUE #259: Add a cluster launch option to control NUMA pinning
@karthikeyann would you please document the changes you did for your NUMA study in a draft PR? 

How that feature fits into Velox-testing is not something we need to solve today.. that could end up tricky to detect system config and optimal pinning.

### PR DESCRIPTION
**Pull request by karthikeyann**
Optimizes multi-GPU Presto worker performance through NUMA-aware process pinning, cuDF batching tuning, and enabling AUTOMATIC join distribution.

### NUMA-aware GPU binding
- Rewrote `launch_presto_servers.sh` to auto-detect the closest NUMA node per GPU via `nvidia-smi topo` and pin workers using `numactl`.
- Installed `numactl` in the Docker image, granted containers `privileged: true`, and mounted `/sys/devices/system/node` for topology visibility.
Fixes https://github.com/rapidsai/velox-testing/issues/259

### cuDF performance tuning
Added to `config_native.properties`:
- `cudf.jit_expression_enabled=false` — avoids JIT warmup penalty across workers.
- `cudf.intra_node_exchange=true` — required for UCX to use NVLink.
- `cudf.partitioned_output_batch_rows=100000000` — reduces exchange overhead.
- `cudf.concat_optimization_enabled=true` / `cudf.batch_size_min_threshold=100000000` — enables rebatching before aggregations.

### Join distribution
- Removed forced `PARTITIONED` override in `generate_presto_config.sh`. UCX exchange now supports BROADCAST, so the optimizer can choose automatically.

### Bug fix
- Fixed `start_presto_helper.sh` to only set `GPU_WORKER_SERVICE` when `SINGLE_CONTAINER=false`.

## Test Plan
- [x] Verify NUMA binding for single-GPU and multi-GPU deployments (check worker logs)
- [x] Run TPC-H/TPC-DS at SF1K+ — no regressions
- [x] Confirm AUTOMATIC join distribution selects BROADCAST where beneficial (EXPLAIN plans)
- [x] Validate batching settings don't cause OOM on large queries

### CODE REVIEW

File: presto/scripts/generate_presto_config.sh [hunk 1]
```diff
@@ -53,8 +53,8 @@ function duplicate_worker_configs() {
     # make cudf.exchange=true if we are running multiple workers
     sed -i "s+cudf.exchange=false+cudf.exchange=true+g" ${worker_native_config}
     # make join-distribution-type=PARTITIONED if we are running multiple workers
-    # (ucx exchange does not currently support BROADCAST partition type)
-    sed -i "s+join-distribution-type=.*+join-distribution-type=PARTITIONED+g" ${coord_native_config}
+    # ucx exchange supports PARTITIONED and BROADCAST partition types
+    # sed -i "s+join-distribution-type=.*+join-distribution-type=PARTITIONED+g" ${coord_native_config}
```
Comment (devavret) [inline presto/scripts/generate_presto_config.sh]: you can just remove these now?

**Review by devavret — APPROVED** [review]

**Review by paul-aiyedun — COMMENTED** [review]
Changes overall look good to me. However, I think we should add a flag that can enable/disable NUMA-aware binding.
